import z from "zod";


  export const CreateRoomDtoSchema = z.object({
    roomNumber: z.coerce.number(),
    roomName: z.string(),
    roomType: z.enum(["SINGLE", "DOUBLE", "TRIPLE", "QUADRUPLE", "STANDARD", "PREMIUM"]),
    floor: z.coerce.number(),
    blockName: z.string(),
    rentPrice: z.coerce.number(),
    depositPrice: z.coerce.number(),
    roomSize: z.coerce.number(),
    availableStatus: z.coerce.boolean(),
    attachedBathrooms: z.coerce.boolean().optional(),
    balconyStatus: z.coerce.boolean().optional(),
    cctvStatus: z.coerce.boolean().optional(),
    airConditioned: z.coerce.boolean().optional().default(false),
    wifi: z.coerce.boolean().optional().default(false),
    refrigerator: z.coerce.boolean().optional().default(false),
    housekeeping: z.coerce.boolean().optional().default(false),
    powerBackup: z.coerce.boolean().optional().default(false),
    bedding: z.coerce.boolean().optional().default(false),
    lift: z.coerce.boolean().optional().default(false),
    drinkingWater: z.coerce.boolean().optional().default(false),
    highSpeedWifi: z.coerce.boolean().optional().default(false),
    hotWaterSupply: z.coerce.boolean().optional().default(false),
    professionalHousekeeping: z.coerce.boolean().optional().default(false),
    laundryFacilities: z.coerce.boolean().optional().default(false),
    biometricEntry: z.coerce.boolean().optional().default(false),
    hotMealsIncluded: z.coerce.boolean().optional().default(false),
    security24x7: z.coerce.boolean().optional().default(false),
    diningArea: z.coerce.boolean().optional().default(false),
    foodMenu: z.record(z.any()).optional(),
    pgId: z.coerce.number(),
  });


export type CreateRoomDtoType = z.infer<typeof CreateRoomDtoSchema>;

export const UpdateRoomDtoSchema = z.object({
  roomNumber: z.coerce.number(),
  roomName: z.string(),
  roomType: z.enum(["SINGLE", "DOUBLE", "TRIPLE", "QUADRUPLE", "STANDARD", "PREMIUM"]),
  floor: z.coerce.number(),
  blockName: z.string(),
  rentPrice: z.coerce.number(),
  depositPrice: z.coerce.number(),
  roomSize: z.coerce.number(),
  availableStatus: z.coerce.boolean(),
  attachedBathrooms: z.coerce.boolean().optional(),
  balconyStatus: z.coerce.boolean().optional(),
  cctvStatus: z.coerce.boolean().optional(),
  airConditioned: z.coerce.boolean().optional().default(false),
  wifi: z.coerce.boolean().optional().default(false),
  refrigerator: z.coerce.boolean().optional().default(false),
  housekeeping: z.coerce.boolean().optional().default(false),
  powerBackup: z.coerce.boolean().optional().default(false),
  bedding: z.coerce.boolean().optional().default(false),
  lift: z.coerce.boolean().optional().default(false),
  drinkingWater: z.coerce.boolean().optional().default(false),
  highSpeedWifi: z.coerce.boolean().optional().default(false),
  hotWaterSupply: z.coerce.boolean().optional().default(false),
  professionalHousekeeping: z.coerce.boolean().optional().default(false),
  laundryFacilities: z.coerce.boolean().optional().default(false),
  biometricEntry: z.coerce.boolean().optional().default(false),
  hotMealsIncluded: z.coerce.boolean().optional().default(false),
  security24x7: z.coerce.boolean().optional().default(false),
  diningArea: z.coerce.boolean().optional().default(false),
  foodMenu: z.record(z.any()).optional(),
  pgId: z.coerce.number(),
});

export type UpdateRoomDtoType = z.infer<typeof UpdateRoomDtoSchema>;

export const GetRoomsDtoSchema = z.object({
  roomNumber: z.number().optional(),
  pgId: z.number().optional(),
  roomName: z.string().optional(),
  roomType: z.enum(["SINGLE", "DOUBLE", "TRIPLE", "QUADRUPLE", "STANDARD", "PREMIUM"]).optional(),
  floor: z.number().optional(),
  blockName: z.string().optional(),
  rentPrice: z.number().optional(),
  depositPrice: z.number().optional(),
  roomSize: z.number().optional(),
  availableStatus: z.boolean().optional(),
  attachedBathrooms: z.boolean().optional(),
  balconyStatus: z.boolean().optional(),
  cctvStatus: z.boolean().optional(),
  airConditioned: z.boolean().optional(),
  wifi: z.boolean().optional(),
  refrigerator: z.boolean().optional(),
  housekeeping: z.boolean().optional(),
  powerBackup: z.boolean().optional(),
  bedding: z.boolean().optional(),
  lift: z.boolean().optional(),
  drinkingWater: z.boolean().optional(),
  highSpeedWifi: z.boolean().optional(),
  hotWaterSupply: z.boolean().optional(),
  professionalHousekeeping: z.boolean().optional(),
  laundryFacilities: z.boolean().optional(),
  biometricEntry: z.boolean().optional(),
  hotMealsIncluded: z.boolean().optional(),
  security24x7: z.boolean().optional(),
  diningArea: z.boolean().optional(),
  foodMenu: z.record(z.any()).optional(), // Optional for filtering
});

export type GetRoomsDtoType = z.infer<typeof GetRoomsDtoSchema>;
