version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9002:9000"  # Change the host port to 9002
      - "9001:9001"  # Keep the console port 9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  minio-data:
